### ISSUE TITLE
✨ Feat: 메인 페이지 개발

### ISSUE THREAD

**Issue by youjuice** [Boongeo/half-time-frontend#21]
### 📄 Description
- 서비스의 첫 화면인 메인 페이지 개발
- 히어로 섹션, 인기 멘토 목록, 기술 스택 탐색 섹션 구현

### ✔️ TO-DO
- [x] 메인 페이지 레이아웃 구현
- [x] 비로그인 상태에서 표시할 메인 페이지 구현
- [ ] 로그인 상태에서 표시할 메인 페이지 구현
- [x] 히어로 섹션 개발 (서비스 소개, CTA 버튼)
- [ ] 인기 멘토 Top 5 섹션 구현

### 🔔 ETC
- Zustand를 활용해 로그인 상태에 따라 다른 UI 렌더링 
- `/(main)` 폴더에 구현
