### ISSUE TITLE
✨ Feat: 사용자 정보 등록 페이지 구현

### ISSUE THREAD

**Issue by youjuice** [Boongeo/half-time-frontend#7]
### 📄 Description
신규 가입자를 위한 필수 정보 입력 페이지 구현

### ✔️ TO-DO
- [x] 필수 정보 입력 폼 개발
- [x] 사용자 정보 업데이트 API 연동
- [x] 프로필 이미지 업로드 기능 구현 (파일 선택 후 미리보기 기능)
- [x] 정보 입력 완료 후 메인 페이지 리다이렉트

### 🔔 ETC
- `/auth/register` 경로에 구현
- 필수 정보 입력 전까지는 서비스 이용 제한
  - nickname, interest, introduction, profileImage 
- 프로필 이미지 업로드 기능 구현
  - 프로필 이미지 FormData 형식으로 백엔드에 전송
  - 이미지 파일은 Base64 형식으로 미리보기 구현
